# Generated by Django 5.1.1 on 2024-09-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farming", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iot",
            name="quadrant",
        ),
        migrations.AddField(
            model_name="quadrant",
            name="iot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quadrant",
                to="farming.iot",
            ),
        ),
    ]
