# Generated by Django 5.1.1 on 2024-09-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farming", "0002_remove_iot_quadrant_quadrant_iot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="level",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("critical", "Critical"),
                ],
                default="info",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="...", null=True),
        ),
    ]
