# Generated by Django 5.1.1 on 2024-09-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farming", "0003_alter_alert_level_alter_alert_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="alerts",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="products",
                to="farming.alert",
            ),
        ),
    ]
