# Generated by Django 5.1.1 on 2024-10-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farming", "0008_iot_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iot",
            old_name="is_active",
            new_name="reactivate",
        ),
    ]
