trigger:
  - develop

name: $(Date:yyyyMMdd)$(Rev:-r)

resources:
  - repo: self
variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'bf3883da-1ce3-4fd8-bee1-261ffb4778b7'
  imageRepository: 'dev-farming-smart-iot-backend'
  containerRegistry: 'acrfarmingsmaralleastus2001.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

stages:
  - template: sonarqube.yml
  - template: build.yml
