stages:
  - stage: SonarQubeAnalysis
    displayName: SonarQube Analysis Stage
    dependsOn: []
    pool:
      name: 'Azure Pipelines'
    jobs:
      - job: SonarQubeAnalysis
        displayName: SonarQube Analysis
        pool:
          name: 'Azure Pipelines'
        continueOnError: true
        steps:
          - task: SonarQubePrepare@6
            inputs:
              SonarQube: 'sonarqube' # Name of the service connection
              scannerMode: 'CLI'
              configMode: 'file'
          - task: SonarQubeAnalyze@6
          - task: SonarQubePublish@6
            inputs:
              pollingTimeoutSec: '300'
