# Generated by Django 5.1.1 on 2024-10-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farming", "0006_iotlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IOTLog",
        ),
        migrations.RemoveField(
            model_name="iot",
            name="battery_level",
        ),
        migrations.RemoveField(
            model_name="iot",
            name="device_id",
        ),
        migrations.RemoveField(
            model_name="iot",
            name="humidity",
        ),
        migrations.RemoveField(
            model_name="iot",
            name="last_measurement",
        ),
        migrations.RemoveField(
            model_name="iot",
            name="temperature",
        ),
        migrations.AlterField(
            model_name="iot",
            name="id",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
