# Generated by Django 5.1.1 on 2024-10-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farming", "0009_rename_is_active_iot_reactivate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iot",
            name="reactivate",
        ),
        migrations.AddField(
            model_name="iot",
            name="activate",
            field=models.BooleanField(default=True),
        ),
    ]
